#!/usr/bin/env python3
"""The OPL synthesiser, compiled into a flat image for SB.MOD.

nano/opl/opl3.c is the chip; nano/opl/oplshim.c gives it three entry points
with plain names.  Both are compiled freestanding for i386 and linked at a
fixed offset (see nano/opl/opl.ld), because modules/sb.asm places the image at
that same offset within itself.  Addresses inside the image are therefore
offsets within the module, which is exactly what the monitor's own selectors
are based on - so the module works wherever the kernel puts it.

Writes build/opl.bin (the image) and build/oplsyms.inc (where things are in
it, for NASM to include).  Run by build.py; run it alone to see the sizes.
"""
import glob
import os
import struct
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OPL = os.path.join(ROOT, 'nano', 'opl')
BUILD = os.path.join(ROOT, 'build')
ORG = 0x6000                            # must match nano/opl/opl.ld and sb.asm

# The names sb.asm calls, and the sizes it needs to reserve.
WANTED = ['opl_reset', 'opl_write', 'opl_render1', 'opl_frame', 'opl_live',
          '__opl_image_end', '__opl_end']


def find_zig():
    for pat in ('zig.exe', 'zig'):
        for c in glob.glob(os.path.join(ROOT, 'tools', 'zig*', pat)):
            return c
    for p in os.environ.get('PATH', '').split(os.pathsep):
        for pat in ('zig.exe', 'zig'):
            c = os.path.join(p, pat)
            if os.path.exists(c):
                return c
    return None


def symbols(elf):
    """Every symbol's address, read out of the ELF itself.

    zig's objdump has no -t, and the symbol table is a dozen lines of struct
    unpacking, so read it here rather than depend on a tool that may not.
    """
    e = open(elf, 'rb').read()
    shoff = struct.unpack_from('<I', e, 32)[0]
    shentsize, shnum = struct.unpack_from('<HH', e, 46)
    secs = [struct.unpack_from('<IIIIIIIIII', e, shoff + i * shentsize)
            for i in range(shnum)]
    out = {}
    for s in secs:
        if s[1] != 2:                   # SHT_SYMTAB
            continue
        strtab = secs[s[6]]
        for j in range(s[5] // 16):
            nm, val = struct.unpack_from('<II', e, s[4] + j * 16)
            end = e.index(b'\0', strtab[4] + nm)
            name = e[strtab[4] + nm:end].decode('latin-1')
            if name:
                out[name] = val
    return out


def stub():
    """No compiler: say so in a form NASM can include, so the module still
    builds and simply has no synthesiser in it."""
    os.makedirs(BUILD, exist_ok=True)
    open(os.path.join(BUILD, 'oplsyms.inc'), 'w', newline='').write(
        '; Generated by tools/build_opl.py: no compiler was found, so SB.MOD
'
        '; is built without a synthesiser and a game's music stays silent.
'
        'OPL_ORG         equ 0x6000
'
        'OPL_END         equ 0x6000
')


def build(quiet=False):
    zig = find_zig()
    if zig is None:
        stub()
        return None                     # no compiler: the module goes without
    os.makedirs(BUILD, exist_ok=True)
    cflags = ['-target', 'x86-freestanding', '-O2', '-std=gnu89', '-w',
              '-ffreestanding', '-fno-builtin', '-fno-stack-protector',
              '-fno-pic', '-fno-pie', '-mno-sse', '-mno-sse2', '-mno-mmx',
              '-fno-strict-aliasing', '-fno-asynchronous-unwind-tables',
              '-fno-unwind-tables', '-nostdinc',
              '-I' + os.path.join(ROOT, 'nano', 'include'), '-I' + OPL]
    r = subprocess.run([zig, 'cc', '-target', 'x86-freestanding',
                        '-print-resource-dir'], capture_output=True, text=True)
    if r.returncode == 0 and r.stdout.strip():
        cflags.append('-I' + os.path.join(r.stdout.strip(), 'include'))

    objs = []
    for src in ('opl3.c', 'oplshim.c'):
        o = os.path.join(BUILD, 'opl_' + src.replace('.c', '.o'))
        r = subprocess.run([zig, 'cc'] + cflags + ['-c', os.path.join(OPL, src),
                                                   '-o', o],
                           capture_output=True, text=True)
        if r.returncode:
            sys.exit('compiling %s failed:\n%s' % (src, r.stderr[:3000]))
        objs.append(o)

    elf = os.path.join(BUILD, 'opl.elf')
    r = subprocess.run([zig, 'cc', '-target', 'x86-freestanding', '-nostdlib',
                        '-static', '-Wl,-T,' + os.path.join(OPL, 'opl.ld'),
                        '-o', elf] + objs, capture_output=True, text=True)
    if r.returncode:
        sys.exit('linking the synthesiser failed:\n' + r.stderr[:3000])

    binary = os.path.join(BUILD, 'opl.bin')
    r = subprocess.run([zig, 'objcopy', '-O', 'binary', elf, binary],
                       capture_output=True, text=True)
    if r.returncode:
        sys.exit('objcopy failed:\n' + r.stderr[:2000])

    syms = symbols(elf)
    missing = [w for w in WANTED if w not in syms]
    if missing:
        sys.exit('the synthesiser is missing: ' + ', '.join(missing))

    image = os.path.getsize(binary)
    lines = ['; Generated by tools/build_opl.py - do not edit.',
             '; Where things are in build/opl.bin, which sb.asm places at',
             '; OPL_ORG within itself.  Every address is an offset in the',
             '; module, which is what the monitor addresses things by.',
             '; NASM %ifdef tests macros, not equates, so this is what the',
             '; module asks about before calling any of the below.',
             '%define HAVE_OPL 1',
             'OPL_ORG         equ 0x%04X' % ORG,
             'OPL_IMAGE       equ 0x%04X' % image,
             'OPL_END         equ 0x%04X' % syms['__opl_end'],
             'OPL_RESET       equ 0x%04X' % syms['opl_reset'],
             'OPL_WRITE       equ 0x%04X' % syms['opl_write'],
             'OPL_RENDER1     equ 0x%04X' % syms['opl_render1'],
             'OPL_FRAME       equ 0x%04X' % syms['opl_frame'],
             'OPL_LIVE        equ 0x%04X' % syms['opl_live'],
             '']
    open(os.path.join(BUILD, 'oplsyms.inc'), 'w', newline='').write(
        '\n'.join(lines))
    if not quiet:
        print('  synthesiser: %d bytes of image, %d with its state '
              '(%04X-%04X)' % (image, syms['__opl_end'] - ORG, ORG,
                               syms['__opl_end']))
    return binary


if __name__ == '__main__':
    if build() is None:
        sys.exit('no zig found: see tools/build_doom.py for where it looks')
