#!/usr/bin/env python3
"""Ember 2.0: the UEFI stub, its shim, and a folder ready for a stick.

    python tools/build_ember2.py

produces build/ember2/EFI/BOOT/BOOTX64.EFI and build/ember2/EMBER.IMG.  Copy
the contents of build/ember2 onto a FAT32 stick and boot it; the firmware's
boot menu will offer the stick.  Secure boot has to be off.

The pieces, in order:
  - tools/mkshimfont.py     the console font          -> build/shimfont.bin
  - ember2/shim.asm         the BIOS-in-a-file, NASM   -> build/shim.bin
  - (this)                  the shim as a C array      -> build/shim_bin.h
  - ember2/stub.c           the UEFI application, zig  -> build/BOOTX64.EFI
  - build.py's ember.img    the disk, unchanged        -> build/ember2/EMBER.IMG
"""
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BUILD = os.path.join(ROOT, 'build')
OUT = os.path.join(BUILD, 'ember2')
sys.path.insert(0, os.path.join(ROOT, 'tools'))
sys.path.insert(0, ROOT)


def build(quiet=False):
    import build as ember_build
    import mkshimfont
    from build_opl import find_zig

    os.makedirs(BUILD, exist_ok=True)
    nasm = ember_build.find_nasm()
    zig = find_zig()
    if zig is None:
        sys.exit('no zig found: see tools/build_doom.py for where it looks')

    mkshimfont.build(quiet)

    shim_bin = os.path.join(BUILD, 'shim.bin')
    r = subprocess.run([nasm, '-f', 'bin', '-I', BUILD + os.sep,
                        '-I', os.path.join(ROOT, 'ember2') + os.sep,
                        os.path.join(ROOT, 'ember2', 'shim.asm'),
                        '-o', shim_bin, '-l', os.path.join(BUILD, 'shim.lst')],
                       capture_output=True, text=True)
    if r.returncode:
        sys.exit('assembling the shim failed:\n' + r.stderr[:4000])
    data = open(shim_bin, 'rb').read()
    if data[:4] != b'EMB2':
        sys.exit('the shim does not begin with its header')
    if len(data) > 0x10000:
        sys.exit('the shim is %d bytes; it has 64 KB' % len(data))
    if not quiet:
        print('  shim: %d bytes -> build/shim.bin' % len(data))

    # the shim as something the C compiler can carry
    with open(os.path.join(BUILD, 'shim_bin.h'), 'w', newline='') as h:
        h.write('/* generated by tools/build_ember2.py from build/shim.bin */\n')
        h.write('static const unsigned char shim_bin[%d] = {\n' % len(data))
        for i in range(0, len(data), 16):
            h.write('  ' + ','.join('0x%02X' % b for b in data[i:i + 16])
                    + ',\n')
        h.write('};\n')

    efi = os.path.join(BUILD, 'EMBER2.EFI')
    r = subprocess.run([zig, 'cc', '-target', 'x86_64-uefi-msvc',
                        '-ffreestanding', '-nostdlib', '-fno-stack-protector',
                        '-fshort-wchar', '-fno-builtin', '-mno-red-zone',
                        '-Wall', '-Wextra', '-O2', '-I' + BUILD,
                        os.path.join(ROOT, 'ember2', 'stub.c'), '-o', efi],
                       capture_output=True, text=True)
    if r.returncode:
        sys.exit('building the stub failed:\n' + r.stderr[:4000])
    if r.stderr.strip() and not quiet:
        print(r.stderr.strip()[:2000])

    # the folder a stick is made from
    img = os.path.join(BUILD, 'ember.img')
    if not os.path.exists(img):
        sys.exit('build/ember.img is missing: run build.py first')
    boot = os.path.join(OUT, 'EFI', 'BOOT')
    os.makedirs(boot, exist_ok=True)
    shutil.copyfile(efi, os.path.join(boot, 'BOOTX64.EFI'))
    shutil.copyfile(img, os.path.join(OUT, 'EMBER.IMG'))
    if not quiet:
        print('  stub: %d bytes -> build/ember2/EFI/BOOT/BOOTX64.EFI'
              % os.path.getsize(efi))
        print('  disk: %d MB     -> build/ember2/EMBER.IMG'
              % (os.path.getsize(img) >> 20))
        print('  copy the contents of build/ember2 onto a FAT32 stick')
    return OUT


if __name__ == '__main__':
    build()
