"""Rasterise a typeface into anti-aliased glyph atlases for the shell.

The shell draws text by blending 8-bit coverage values, which is what makes
it look like text and not like a BIOS font.  Doing the rasterising here, at
build time, means the shell carries no font machinery at all: just bytes.

    python tools/mkfont.py            -> build/guifont.h

Three sizes are produced: small for labels, normal for most of the
interface, and large for titles.  Only printable ASCII is included; the
shell substitutes a blank for anything else.
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WIN_FONTS = r"C:\Windows\Fonts"
FIRST, LAST = 32, 126

# (name, file, pixel size).  Barlow is an open (SIL OFL) family, condensed
# enough to feel technical without being hard to read.
FACES = [
    ("small",  "BarlowCondensed-Medium.ttf",   16),
    ("normal", "BarlowCondensed-Medium.ttf",   19),
    ("bold",   "BarlowCondensed-SemiBold.ttf", 19),
    ("title",  "BarlowCondensed-SemiBold.ttf", 24),
    ("clock",  "BarlowCondensed-SemiBold.ttf", 40),
]
FALLBACKS = ["Lato-Regular.ttf", "arial.ttf", "segoeui.ttf"]


def find_font(name):
    for cand in (os.path.join(WIN_FONTS, name),
                 os.path.join(ROOT, "tools", "fonts", name)):
        if os.path.exists(cand):
            return cand
    for fb in FALLBACKS:
        cand = os.path.join(WIN_FONTS, fb)
        if os.path.exists(cand):
            print("  ! %s not found, using %s" % (name, fb))
            return cand
    sys.exit("no usable font found; put a .ttf in tools/fonts/")


def render_face(label, filename, size, out):
    font = ImageFont.truetype(find_font(filename), size)
    ascent, descent = font.getmetrics()
    height = ascent + descent
    glyphs, pixels = [], bytearray()
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        box = font.getbbox(ch)                  # (x0, y0, x1, y1)
        advance = int(round(font.getlength(ch)))
        if box is None or box[2] <= box[0] or box[3] <= box[1]:
            glyphs.append((0, 0, 0, 0, advance, len(pixels)))
            continue
        x0, y0, x1, y1 = box
        w, h = x1 - x0, y1 - y0
        img = Image.new("L", (w, h), 0)
        d = ImageDraw.Draw(img)
        d.text((-x0, -y0), ch, font=font, fill=255)
        glyphs.append((w, h, x0, y0, advance, len(pixels)))
        pixels += img.tobytes()

    out.write("/* %s: %s at %dpx */\n" % (label, filename, size))
    out.write("static const unsigned char font_%s_pixels[] = {\n" % label)
    for i in range(0, len(pixels), 24):
        out.write("    " + ",".join("%d" % b for b in pixels[i:i + 24]) + ",\n")
    out.write("};\n")
    out.write("static const struct glyph font_%s_glyphs[] = {\n" % label)
    for w, h, bx, by, adv, off in glyphs:
        out.write("    {%d,%d,%d,%d,%d,%d},\n" % (w, h, bx, by, adv, off))
    out.write("};\n")
    out.write("static const struct font font_%s = { font_%s_glyphs, "
              "font_%s_pixels, %d, %d, %d };\n\n"
              % (label, label, label, height, ascent, FIRST))
    print("  %-7s %2dpx  height %2d  %6d bytes of coverage"
          % (label, size, height, len(pixels)))
    return len(pixels)


def main():
    out_path = os.path.join(ROOT, "build", "guifont.h")
    total = 0
    with open(out_path, "w") as out:
        out.write("/* Generated by tools/mkfont.py - do not edit. */\n"
                  "#ifndef GUIFONT_H\n#define GUIFONT_H\n\n"
                  "struct glyph { short w, h, bx, by, advance; int offset; };\n"
                  "struct font { const struct glyph *glyphs; "
                  "const unsigned char *pixels; short height, ascent, first; };\n\n")
        for label, filename, size in FACES:
            total += render_face(label, filename, size, out)
        out.write("#endif\n")
    print("  %s: %d bytes of glyph coverage in all" % (out_path, total))


if __name__ == "__main__":
    main()
