"""Turn the artwork in graphics/ into something the desktop can draw.

The pictures are PNGs with transparency; the desktop has no image decoder
and does not need one, because the conversion happens here.  Each becomes
straight RGBA bytes at the size it will be drawn, so putting one on screen
is a blend and nothing more.

    python tools/mkicons.py     -> build/guiart.h
"""
import os
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(ROOT, "graphics")
ICON_PX = 56                    # what a desktop icon is drawn at
CRYSTAL_W = 132                 # the gem at the top of the screen

# the file in graphics/, and the name the C code knows it by
ICONS = [
    ("file_icon.png",     "folder"),
    ("music_icon.png",    "music"),
    ("terminal_icon.png", "terminal"),
    ("calc_icon.png",     "calc"),
    ("ic_icon.png",       "chip"),
    ("info_icon.png",     "info"),
    ("book_icon.png",     "book"),
    ("note_icon.png",     "note"),
    ("paint_icon.png",    "paint"),
    ("gear_icon.png",     "gear"),
    ("computer_icon.png", "computer"),
    ("clock_icon.png",    "clock"),
    ("globe_icon.png",    "globe"),
    ("lock_icon.png",     "lock"),
    ("trash_icon.png",    "trash"),
    ("wrench_icon.png",   "wrench"),
]


def emit(out, name, im):
    """Write one picture as RGBA bytes, alpha last, ready to blend."""
    im = im.convert("RGBA")
    w, h = im.size
    data = bytearray()
    for pixel in im.getdata():
        r, g, b, a = pixel
        data += bytes((b, g, r, a))         # the order the screen uses
    out.write("static const unsigned char art_%s_data[] = {\n" % name)
    for i in range(0, len(data), 24):
        out.write("    " + ",".join("%d" % v for v in data[i:i + 24]) + ",\n")
    out.write("};\n")
    out.write("static const struct image art_%s = { %d, %d, art_%s_data };\n\n"
              % (name, w, h, name))
    return len(data)


def main():
    out_path = os.path.join(ROOT, "build", "guiart.h")
    total = 0
    missing = []
    with open(out_path, "w") as out:
        out.write("/* Generated by tools/mkicons.py - do not edit. */\n"
                  "#ifndef GUIART_H\n#define GUIART_H\n\n"
                  "struct image { short w, h; const unsigned char *bgra; };\n\n")

        for filename, name in ICONS:
            path = os.path.join(ART, filename)
            if not os.path.exists(path):
                missing.append(filename)
                continue
            im = Image.open(path).resize((ICON_PX, ICON_PX), Image.LANCZOS)
            total += emit(out, name, im)

        crystal = os.path.join(ART, "E-start.png")
        if os.path.exists(crystal):
            im = Image.open(crystal)
            h = round(im.height * CRYSTAL_W / im.width)
            im = im.resize((CRYSTAL_W, h), Image.LANCZOS)
            total += emit(out, "crystal", im)
            out.write("#define HAVE_CRYSTAL_ART 1\n")
        else:
            missing.append("E-start.png")

        out.write("\n#endif\n")

    if missing:
        print("  ! not found in graphics/: " + ", ".join(missing))
    print("  %s: %d pictures, %d KB of pixels"
          % (out_path, len(ICONS) - len(missing) + 1, total // 1024))


if __name__ == "__main__":
    main()
