#!/usr/bin/env python3
"""Draw Reversi's text fonts into a C++ header (build/reversi/gen/assets.h).

Called by tools/build_reversi.py.  The text is drawn here, at build time,
from the DejaVu Sans fonts (Bitstream Vera license, see docs/REVERSI.md) and
embedded in REVERSI.N32 as antialiased alpha masks.  Ember has no font
rasteriser, and does not need one: the game only ever draws these few sizes.

This is tools/mkchessart.py without the chess pieces; the header has the
same shape, because gfx.cpp is shared with Chess.
"""
import os

from PIL import Image, ImageDraw, ImageFont

# name, file, pixel size
FONTS = [
    ('small', 'DejaVuSans.ttf', 12),
    ('body', 'DejaVuSans.ttf', 14),
    ('bold', 'DejaVuSans-Bold.ttf', 14),
    ('coord', 'DejaVuSans-Bold.ttf', 11),
    ('large', 'DejaVuSans-Bold.ttf', 18),
    ('title', 'DejaVuSans-Bold.ttf', 26),
    ('huge', 'DejaVuSans-Bold.ttf', 36),
    ('move', 'DejaVuSans.ttf', 15),
    ('moveb', 'DejaVuSans-Bold.ttf', 15),
]

# Characters 32..126, and a few beyond ASCII given codes 128.. in strings.
EXTRA = ['·', '½', '…', '−', '◀', '▶', '—', '×']


def c_bytes(data):
    out = []
    for i in range(0, len(data), 24):
        out.append(','.join(str(b) for b in data[i:i + 24]))
    return ',\n'.join(out)


def font_atlas(ttf, px):
    font = ImageFont.truetype(ttf, px)
    ascent, descent = font.getmetrics()
    chars = [chr(c) for c in range(32, 127)] + EXTRA
    glyphs, pixels = [], bytearray()
    for ch in chars:
        advance = int(round(font.getlength(ch)))
        bbox = font.getbbox(ch)
        if bbox is None or bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
            glyphs.append((0, 0, 0, 0, advance, len(pixels)))
            continue
        x0, y0, x1, y1 = bbox
        w, h = x1 - x0, y1 - y0
        img = Image.new('L', (w, h), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255)
        glyphs.append((x0, y0 - ascent, w, h, advance, len(pixels)))
        pixels += img.tobytes()
    return ascent, descent, glyphs, pixels


def generate(font_dir, out_dir):
    """assets.h in out_dir."""
    lines = ['// Generated by tools/mkreversiart.py from the DejaVu fonts. Do not edit.',
             '#pragma once', '#include <cstdint>', '',
             'struct PieceMasks { const uint8_t* hull; const uint8_t* line; const uint8_t* solid; const uint8_t* shadow; };',
             'struct PieceSet { int size; PieceMasks piece[6]; };  // P N B R Q K',
             'struct Glyph { int16_t x, y; uint8_t w, h, advance; uint32_t offset; };',
             'struct Font { int ascent, descent, height; const Glyph* glyph; const uint8_t* pixels; };',
             '',
             '// No pieces: the discs are drawn as circles.  gfx.cpp still refers to these.',
             'static const PieceSet PieceSets[] = { { 0, {} } };',
             'static const int PieceSetCount = 0;',
             '']

    for name, file, px in FONTS:
        ascent, descent, glyphs, pixels = font_atlas(os.path.join(font_dir, file), px)
        lines.append('static const uint8_t font_%s_pixels[] = {\n%s };' % (name, c_bytes(pixels) or '0'))
        lines.append('static const Glyph font_%s_glyphs[] = {\n%s };' % (
            name, ',\n'.join('  { %d, %d, %d, %d, %d, %d }' % g for g in glyphs)))
        lines.append('static const Font font_%s = { %d, %d, %d, font_%s_glyphs, font_%s_pixels };'
                     % (name, ascent, descent, ascent + descent, name, name))
    lines.append('')
    path = os.path.join(out_dir, 'assets.h')
    with open(path + '.tmp', 'w') as f:
        f.write('\n'.join(lines))
    os.replace(path + '.tmp', path)
