"""Tables the desktop needs at run time, worked out here instead.

A sine table for the spectrum analyser's transform, and the band edges it
groups the result into.  Both are fixed at build time so the shell carries
no trigonometry and no floating point at all.

    python tools/mktables.py    -> build/guitables.h
"""
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
N = 256                         # points in the transform
BARS = 24                       # bars drawn


def main():
    out = os.path.join(ROOT, "build", "guitables.h")
    with open(out, "w") as f:
        f.write("/* Generated by tools/mktables.py - do not edit. */\n"
                "#ifndef GUITABLES_H\n#define GUITABLES_H\n\n")
        f.write("#define FFT_N    %d\n#define FFT_BARS %d\n\n" % (N, BARS))

        # sin(2*pi*i/N) in Q15, one full turn
        f.write("static const short sin_q15[%d] = {\n" % N)
        vals = [int(round(math.sin(2 * math.pi * i / N) * 32767)) for i in range(N)]
        for i in range(0, N, 12):
            f.write("    " + ",".join("%d" % v for v in vals[i:i + 12]) + ",\n")
        f.write("};\n\n")

        # the order the transform needs its input in
        bits = N.bit_length() - 1
        rev = []
        for i in range(N):
            r = 0
            for b in range(bits):
                if i & (1 << b):
                    r |= 1 << (bits - 1 - b)
            rev.append(r)
        f.write("static const unsigned char bit_rev[%d] = {\n" % N)
        for i in range(0, N, 16):
            f.write("    " + ",".join("%d" % v for v in rev[i:i + 16]) + ",\n")
        f.write("};\n\n")

        # bars are spaced by ear, not evenly: low notes get more room
        edges = []
        for b in range(BARS + 1):
            lo, hi = 2.0, N / 2.0
            e = lo * (hi / lo) ** (b / float(BARS))
            edges.append(min(int(round(e)), N // 2))
        for b in range(1, len(edges)):           # each bar covers at least one bin
            if edges[b] <= edges[b - 1]:
                edges[b] = edges[b - 1] + 1
        f.write("static const short bar_edge[%d] = {\n    " % (BARS + 1))
        f.write(",".join("%d" % e for e in edges))
        f.write("\n};\n\n#endif\n")
    print("  %s: %d-point transform, %d bars" % (out, N, BARS))


if __name__ == "__main__":
    main()
